server:
  port: 8081

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auditoria-service
              uri: lb://AUDITORIA
              predicates:
                - Path=/api/auditoria/**
            - id: reservas-service
              uri: lb://RESERVAS
              predicates:
                - Path=/api/reservas/**
            - id: proveedores-service
              uri: lb://PROVEEDORES
              predicates:
                - Path=/api/proveedor/**
            - id: notificaciones-service
              uri: lb://NOTIFICACIONES
              predicates:
                - Path=/api/notificaciones/**

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
