server:
  port: ${PORT:8081}

spring:
  application:
    name: api-gateway

  cloud:
    discovery:
      enabled: true
    gateway:
      server:
        webmvc:
          routes:
            - id: auditoria-service
              uri: ${AUDITORIA_SERVICE_URL:http://localhost:8080}
              predicates:
                - Path=/api/auditoria/**
            - id: reservas-service
              uri: ${RESERVAS_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/api/reservas/**
            - id: proveedores-service
              uri: ${PROVEEDORES_SERVICE_URL:http://localhost:8083}
              predicates:
                - Path=/api/proveedor/**
            - id: notificaciones-service
              uri: ${NOTIFICACIONES_SERVICE_URL:http://localhost:8084}
              predicates:
                - Path=/api/notificaciones/**
            - id: prestamos-service
              uri: ${PRESTAMOS_SERVICE_URL:http://localhost:8085}
              predicates:
                - Path=/api/prestamos/**
            - id: devoluciones-service
              uri: ${DEVOLUCIONES_SERVICE_URL:http://localhost:8086}
              predicates:
                - Path=/api/devoluciones/**
            - id: multas-service
              uri: ${MULTAS_SERVICE_URL:http://localhost:8087}
              predicates:
                - Path=/api/multas/**
            - id: usuarios-service
              uri: ${USUARIOS_SERVICE_URL:http://localhost:8088}
              predicates:
                - Path=/api/usuarios/**

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
