server:
  port: 8081

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auditoria-service
              uri: lb://AUDITORIA
              predicates:
                - Path=/api/auditoria/**
            - id: reservas-service
              uri: lb://RESERVAS
              predicates:
                - Path=/api/reservas/**
            - id: proveedores-service
              uri: lb://PROVEEDORES
              predicates:
                - Path=/api/proveedor/**
            - id: notificaciones-service
              uri: lb://NOTIFICACIONES
              predicates:
                - Path=/api/notificaciones/**
            - id: prestamos-service
              uri: lb://PRESTAMOS
              predicates:
                - Path=/api/prestamos/**
            - id: devoluciones-service
              uri: lb://DEVOLUCIONES
              predicates:
                - Path=/api/devoluciones/**
            - id: multas-service
              uri: lb://MULTAS
              predicates:
                - Path=/api/multas/**
            - id: usuarios-service
              uri: lb://USUARIOS
              predicates:
                - Path=/api/usuarios/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
