services:

  mysql:
    image: mysql:8.4
    container_name: usuarios-mysql
    restart: always
    environment:
      MYSQL_DATABASE: dev_usuarios
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3314:3306"
    volumes:
      - ../docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - usuarios-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s

  eurekaserver:
    build:
      context: ../eurekaserver
    image: eurekaserver:1.0
    container_name: usuarios-eurekaserver
    ports:
      - "8761:8761"
    networks:
      - usuarios-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      timeout: 10s
      retries: 5
      interval: 10s

  usuarios:
    build:
      context: .
    image: usuarios:1.0
    container_name: usuarios-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dev_usuarios
    depends_on:
      mysql:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    ports:
      - "8088:8088"
    networks:
      - usuarios-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/actuator/health"]
      timeout: 10s
      retries: 5
      interval: 10s

networks:
  usuarios-network:
    driver: bridge
