spring:
  application:
    name: reservas

  datasource:
    url: jdbc:mysql://mysql:3306/dev_reservas
    username: dev
    password: dev123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8082

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    dev.diemigo.reservas: INFO
    org.hibernate.SQL: WARN
