services:

  mysql:
    image: mysql:8.4
    container_name: libros-mysql
    restart: always
    environment:
      MYSQL_DATABASE: dev_libros
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3315:3306"
    volumes:
      - ../docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - libros-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s

  eurekaserver:
    build:
      context: ../eurekaserver
    image: eurekaserver:1.0
    container_name: libros-eurekaserver
    ports:
      - "8761:8761"
    networks:
      - libros-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      timeout: 10s
      retries: 5
      interval: 10s

  libros:
    build:
      context: .
    image: libros:1.0
    container_name: libros-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dev_libros
    depends_on:
      mysql:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    ports:
      - "8089:8089"
    networks:
      - libros-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8089/actuator/health"]
      timeout: 10s
      retries: 5
      interval: 10s

networks:
  libros-network:
    driver: bridge
