spring.application.name=dev.auditoria
spring.datasource.url=jdbc:mysql://localhost:3306/auditoria_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
springdoc.swagger-ui.path=/swagger-ui.html

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false

logging.level.dev.diemigo.dev.auditoria=DEBUG
logging.level.org.hibernate.SQL=warn

