services:

  mysql:
    image: mysql:8.4
    container_name: reservas-mysql
    restart: always
    environment:
      MYSQL_DATABASE: dev_reservas
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3308:3306"
    volumes:
      - ../docker/mysql/init:/docker-entrypoint-initdb.d

  eurekaserver:
    build:
      context: ../eurekaserver
    image: eurekaserver:1.0
    container_name: reservas-eurekaserver
    ports:
      - "8761:8761"

  reservas:
    build:
      context: .
    image: reservas:1.0
    container_name: reservas-service
    depends_on:
      - mysql
      - eurekaserver
    ports:
      - "8082:8082"
